name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog and bump production version
        if: github.ref == 'refs/heads/main'
        id: cz-production
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Init UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build Package
        run: uv build --all-packages

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.REVISION }}
          body_path: "body.md"
          files: dist/**

      - name: Upload to Pypi
        run: uv publish
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.STAINLY_PYPI }}

  build-docs:
    name: build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: build
        run: uv run --group docs mkdocs build
      - uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: site/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
